### ISSUE TITLE
看谷歌的论文说movenet效果很好，怎么实际使用起来不怎样啊

### ISSUE THREAD

**Issue by FuckAnyProblem** [deepkolos/wxmp-tensorflow#10]
顺便想问一下微信小程序不支持movenet的多人吗

**Comment by deepkolos** [comment]
@FuckAnyProblem 支持, 需要参数开启, 可以翻翻代码, 手机用的是webgl1做推理, 也就那点性能没啥好办法
代码搜这个字段吧 `MOVENET_SINGLE_POSE_ESTIMATION_CONFIG`

```ts
export const MOVENET_SINGLE_POSE_ESTIMATION_CONFIG: MoveNetEstimationConfig = {
  maxPoses: 1
};
```

**Comment by FuckAnyProblem** [comment]
> @FuckAnyProblem 支持, 需要参数开启, 可以翻翻代码, 手机用的是webgl1做推理, 也就那点性能没啥好办法 代码搜这个字段吧 `MOVENET_SINGLE_POSE_ESTIMATION_CONFIG`
> 
> ```ts
> export const MOVENET_SINGLE_POSE_ESTIMATION_CONFIG: MoveNetEstimationConfig = {
>   maxPoses: 1
> };
> ```

谢谢前辈

**Comment by FuckAnyProblem** [comment]
> @FuckAnyProblem 支持, 需要参数开启, 可以翻翻代码, 手机用的是webgl1做推理, 也就那点性能没啥好办法 代码搜这个字段吧 `MOVENET_SINGLE_POSE_ESTIMATION_CONFIG`
> 
> ```ts
> export const MOVENET_SINGLE_POSE_ESTIMATION_CONFIG: MoveNetEstimationConfig = {
>   maxPoses: 1
> };
> ```

改了参数还是不行，我看了下代码是支持画多人的，但是您的源码中并没有添加movenet的多人模型，尝试依葫芦画瓢添加后报错了。
