### ISSUE TITLE
blazepose有运行成功过吗？

### ISSUE THREAD

**Issue by CodeLiSW** [deepkolos/wxmp-tensorflow#3]
movenet，posenet我都跑通了，唯独blazepose无法正常运行，runtime设置的tfjs，landmarkmodel和detectormodel都下载本地设置好url了，运行estimatePoses会报错，heatmap与landmark的length不一致。有什么解决方法吗？

**Comment by deepkolos** [comment]
是blazepose tfjs版本还是mediapipe版本？mediapipe版本估计无法运行，mediapipe的需要wasm，得微信适配WXWebAssembly

**Comment by deepkolos** [comment]
@CodeLiSW 代码更新了，tfjs版能跑起来，mediapipe估计是难，得自己适配wasm版了，模型地址还没替换为国内的，自己拉项目自行替换下

![图片](https://user-images.githubusercontent.com/12824616/124383115-5375d580-dcfd-11eb-8771-ac919e632dda.png)
