### ISSUE TITLE
movenet运行失败的问题

### ISSUE THREAD

**Issue by AaronCather** [deepkolos/wxmp-tensorflow#7]
您好：
在手机上验证了下movenet，直接卡死在初始化了
报错是这个
ERROR: 0:169: 'expression' :  left of '[' is not of type array, matrix, or vector  
painter.js:1  169              out_of_bounds = out_of_bounds || index >= paramsShape[j];        
painter.js:1 170              flattenIndex += index * strides[j];
171            }
172            setOutput(out_of_bounds ? 0.0 : getX(flattenIndex, coords[1]));
173          }
174        
不知道有没有什么办法可以解决卡死初始化问题？希望得到您的回复

**Comment by deepkolos** [comment]
@AaronCather 是demo中有movenet 请问是ios手机么, 我刚用红米note10pro扫, 这个是正常的

![](https://camo.githubusercontent.com/09a969091d13f465a75f453f8e1a16ed641f4977d13a69fb3d8797bffcff1b0c/68747470733a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f3235323035302d633939303731646334626636313138352e6a70673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

**Comment by AaronCather** [comment]
您这个是正常的，我是说我的编译问题，可以先不看了。
再请教个问题啊，现在movenet小程序支持多人了吗？

**Comment by deepkolos** [comment]
https://github.com/deepkolos/wxmp-tensorflow/blob/4c7e612bf38401f0753500d5b35dd49ff1a074b8/tfjs-models-sync/pose-detection/movenet/constants.ts#L39
可以看看这个文件 @AaronCather

**Comment by AaronCather** [comment]
好的，谢谢大佬

**Comment by FuckAnyProblem** [comment]
> 好的，谢谢大佬

你多人有试吗，最终可以吗

**Comment by AaronCather** [comment]
没成功

**Comment by FuckAnyProblem** [comment]
> 没成功

好吧

**Comment by AaronCather** [comment]
> > 没成功
> 
> 好吧

你那边实现了横屏了吗？

**Comment by FuckAnyProblem** [comment]
> > > 没成功
> > 
> > 
> > 好吧
> 
> 你那边实现了横屏了吗？

我没有这个需求
